edition = "2024"

brace_style                         = "PreferSameLine"
format_macro_matchers               = true
group_imports                       = "StdExternalCrate"
hard_tabs                           = true
hex_literal_case                    = "Lower"
imports_granularity                 = "Crate"
match_arm_blocks                    = false
max_width                           = 84
normalize_doc_attributes            = true
reorder_impl_items                  = true
reorder_imports                     = true
short_array_element_width_threshold = 20
unstable_features                   = true
use_field_init_shorthand            = true
# use_small_heuristics = "Default"
use_try_shorthand = true

# hard_tabs                  = false
match_block_trailing_comma = true
merge_derives              = true
newline_style              = "Unix"
reorder_modules            = true
tab_spaces                 = 4
use_small_heuristics       = "Max"

# -----------------------------------
# Unstable options we would like to use in future
# -----------------------------------

# blank_lines_lower_bound = 1
# condense_wildcard_suffixes = true
# enum_discrim_align_threshold = 20
# fn_single_line = true
# format_code_in_doc_comments = true
# format_strings = true
# group_imports = "StdExternalCrate"
# hex_literal_case = "Lower"
# imports_granularity = "Module"
# imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 50
# match_arm_blocks = true
# normalize_comments = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# reorder_impl_items = true
# struct_field_align_threshold = 20
# struct_lit_single_line = true
# trailing_comma = "Vertical"
# trailing_semicolon = true
# where_single_line = true
# wrap_comments = true
